// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `ars-remote.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ars.invoke.remote.slice;

final class _AMD_Resource_invoke extends IceInternal.IncomingAsync implements AMD_Resource_invoke {
    public _AMD_Resource_invoke(IceInternal.Incoming in) {
        super(in);
    }

    public void ice_response(Iresult __ret) {
        if (__validateResponse(true)) {
            try {
                IceInternal.BasicStream __os = this.__startWriteParams(Ice.FormatType.DefaultFormat);
                __os.writeObject(__ret);
                __os.writePendingObjects();
                this.__endWriteParams(true);
            } catch (Ice.LocalException __ex) {
                __exception(__ex);
                return;
            }
            __response();
        }
    }
}
