// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `ars-remote.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ars.invoke.remote.slice;

public final class IstreamHolder extends Ice.ObjectHolderBase<Istream> {
	public IstreamHolder() {
	}

	public IstreamHolder(Istream value) {
		this.value = value;
	}

	public void patch(Ice.Object v) {
		if (v == null || v instanceof Istream) {
			value = (Istream) v;
		} else {
			IceInternal.Ex.throwUOE(type(), v);
		}
	}

	public String type() {
		return Istream.ice_staticId();
	}
}
