// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `ars-remote.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ars.invoke.remote.slice;

/**
 * 远程资源
 *
 **/
public interface Resource extends Ice.Object, _ResourceOperations, _ResourceOperationsNC {
	public static final String ice_staticId = "::ars::invoke::remote::slice::Resource";

	public static final long serialVersionUID = -1764459085L;
}
